/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SendPrescriptionRouteImport } from './routes/send-prescription'
import { Route as HealthTipsRouteImport } from './routes/health-tips'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HealthTipsSlugRouteImport } from './routes/health-tips.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SendPrescriptionRoute = SendPrescriptionRouteImport.update({
  id: '/send-prescription',
  path: '/send-prescription',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthTipsRoute = HealthTipsRouteImport.update({
  id: '/health-tips',
  path: '/health-tips',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthTipsSlugRoute = HealthTipsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => HealthTipsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/health-tips': typeof HealthTipsRouteWithChildren
  '/send-prescription': typeof SendPrescriptionRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/health-tips/$slug': typeof HealthTipsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/health-tips': typeof HealthTipsRouteWithChildren
  '/send-prescription': typeof SendPrescriptionRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/health-tips/$slug': typeof HealthTipsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/health-tips': typeof HealthTipsRouteWithChildren
  '/send-prescription': typeof SendPrescriptionRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/health-tips/$slug': typeof HealthTipsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/health-tips'
    | '/send-prescription'
    | '/shop'
    | '/sitemap.xml'
    | '/health-tips/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/health-tips'
    | '/send-prescription'
    | '/shop'
    | '/sitemap.xml'
    | '/health-tips/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/health-tips'
    | '/send-prescription'
    | '/shop'
    | '/sitemap.xml'
    | '/health-tips/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  HealthTipsRoute: typeof HealthTipsRouteWithChildren
  SendPrescriptionRoute: typeof SendPrescriptionRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-prescription': {
      id: '/send-prescription'
      path: '/send-prescription'
      fullPath: '/send-prescription'
      preLoaderRoute: typeof SendPrescriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-tips': {
      id: '/health-tips'
      path: '/health-tips'
      fullPath: '/health-tips'
      preLoaderRoute: typeof HealthTipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-tips/$slug': {
      id: '/health-tips/$slug'
      path: '/$slug'
      fullPath: '/health-tips/$slug'
      preLoaderRoute: typeof HealthTipsSlugRouteImport
      parentRoute: typeof HealthTipsRoute
    }
  }
}

interface HealthTipsRouteChildren {
  HealthTipsSlugRoute: typeof HealthTipsSlugRoute
}

const HealthTipsRouteChildren: HealthTipsRouteChildren = {
  HealthTipsSlugRoute: HealthTipsSlugRoute,
}

const HealthTipsRouteWithChildren = HealthTipsRoute._addFileChildren(
  HealthTipsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  HealthTipsRoute: HealthTipsRouteWithChildren,
  SendPrescriptionRoute: SendPrescriptionRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
